//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNGTTranslator.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VNGTTranslator.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 About VNGT Translator 的當地語系化字串。
        /// </summary>
        public static string AboutPage_Text_AboutProgram {
            get {
                return ResourceManager.GetString("AboutPage.Text.AboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Feature Request or Issue 的當地語系化字串。
        /// </summary>
        public static string AboutPage_Text_FeatureAndIssue {
            get {
                return ResourceManager.GetString("AboutPage.Text.FeatureAndIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Version 的當地語系化字串。
        /// </summary>
        public static string AboutPage_Text_Version {
            get {
                return ResourceManager.GetString("AboutPage.Text.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Website 的當地語系化字串。
        /// </summary>
        public static string AboutPage_Text_WebSite {
            get {
                return ResourceManager.GetString("AboutPage.Text.WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Display Language(Effective after restart) 的當地語系化字串。
        /// </summary>
        public static string AppSettingPage_Text_DisplayLanguage {
            get {
                return ResourceManager.GetString("AppSettingPage.Text.DisplayLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Close 的當地語系化字串。
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save 的當地語系化字串。
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select Color 的當地語系化字串。
        /// </summary>
        public static string ColorPicker_Text_Title {
            get {
                return ResourceManager.GetString("ColorPicker.Text.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Can&apos;t capture image 的當地語系化字串。
        /// </summary>
        public static string Error_CanNotCaptureImage {
            get {
                return ResourceManager.GetString("Error.CanNotCaptureImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Insert Hook Code Failed 的當地語系化字串。
        /// </summary>
        public static string Error_InsertHookCodeFailed {
            get {
                return ResourceManager.GetString("Error.InsertHookCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No OCR Provider can use 的當地語系化字串。
        /// </summary>
        public static string Error_NoOCRCanUse {
            get {
                return ResourceManager.GetString("Error.NoOCRCanUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No TTS Provider can use 的當地語系化字串。
        /// </summary>
        public static string Error_NoTTSCanUse {
            get {
                return ResourceManager.GetString("Error.NoTTSCanUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 History 的當地語系化字串。
        /// </summary>
        public static string HistoryWindow_Text_Title {
            get {
                return ResourceManager.GetString("HistoryWindow.Text.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Close 的當地語系化字串。
        /// </summary>
        public static string HookSelectWindow_Text_Close {
            get {
                return ResourceManager.GetString("HookSelectWindow.Text.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm 的當地語系化字串。
        /// </summary>
        public static string HookSelectWindow_Text_Confirm {
            get {
                return ResourceManager.GetString("HookSelectWindow.Text.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter the Hook Code 的當地語系化字串。
        /// </summary>
        public static string HookSelectWindow_Text_EnterHookCodeHint {
            get {
                return ResourceManager.GetString("HookSelectWindow.Text.EnterHookCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 let the text change 的當地語系化字串。
        /// </summary>
        public static string HookSelectWindow_Text_Hint {
            get {
                return ResourceManager.GetString("HookSelectWindow.Text.Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Manually Add H-Code 的當地語系化字串。
        /// </summary>
        public static string HookSelectWindow_Text_ManuallyAddHookCode {
            get {
                return ResourceManager.GetString("HookSelectWindow.Text.ManuallyAddHookCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select Hook Code 的當地語系化字串。
        /// </summary>
        public static string HookSelectWindow_Text_Title {
            get {
                return ResourceManager.GetString("HookSelectWindow.Text.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hook Mode 的當地語系化字串。
        /// </summary>
        public static string ProcessSelectWindow_HookMode {
            get {
                return ResourceManager.GetString("ProcessSelectWindow.HookMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OCR Mode 的當地語系化字串。
        /// </summary>
        public static string ProcessSelectWindow_OCRMode {
            get {
                return ResourceManager.GetString("ProcessSelectWindow.OCRMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Drag to the target window 的當地語系化字串。
        /// </summary>
        public static string ProcessSelectWindow_OCRMode_DragToTargetWindow {
            get {
                return ResourceManager.GetString("ProcessSelectWindow.OCRMode.DragToTargetWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OCR Language 的當地語系化字串。
        /// </summary>
        public static string ProcessSelectWindow_OCRMode_OCRLanguage {
            get {
                return ResourceManager.GetString("ProcessSelectWindow.OCRMode.OCRLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PreProcess 的當地語系化字串。
        /// </summary>
        public static string ProcessSelectWindow_OCRMode_PreProcess {
            get {
                return ResourceManager.GetString("ProcessSelectWindow.OCRMode.PreProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Refresh Region 的當地語系化字串。
        /// </summary>
        public static string ProcessSelectWindow_OCRMode_RefreshSelectRegion {
            get {
                return ResourceManager.GetString("ProcessSelectWindow.OCRMode.RefreshSelectRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select Region 的當地語系化字串。
        /// </summary>
        public static string ProcessSelectWindow_OCRMode_SelectRegion {
            get {
                return ResourceManager.GetString("ProcessSelectWindow.OCRMode.SelectRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Target Window 的當地語系化字串。
        /// </summary>
        public static string ProcessSelectWindow_OCRMode_TargetWindow {
            get {
                return ResourceManager.GetString("ProcessSelectWindow.OCRMode.TargetWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Test OCR 的當地語系化字串。
        /// </summary>
        public static string ProcessSelectWindow_OCRMode_TestOCR {
            get {
                return ResourceManager.GetString("ProcessSelectWindow.OCRMode.TestOCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use Screenshot 的當地語系化字串。
        /// </summary>
        public static string ProcessSelectWindow_OCRMode_UseScreenshot {
            get {
                return ResourceManager.GetString("ProcessSelectWindow.OCRMode.UseScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select Game Process 的當地語系化字串。
        /// </summary>
        public static string ProcessSelectWindow_SelectGameProcess {
            get {
                return ResourceManager.GetString("ProcessSelectWindow.SelectGameProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select Process 的當地語系化字串。
        /// </summary>
        public static string ProcessSelectWindow_SelectProcessWindowHeader {
            get {
                return ResourceManager.GetString("ProcessSelectWindow.SelectProcessWindowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Proxy 的當地語系化字串。
        /// </summary>
        public static string ProxySettingPage_Text_Proxy {
            get {
                return ResourceManager.GetString("ProxySettingPage.Text.Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use Proxy 的當地語系化字串。
        /// </summary>
        public static string ProxySettingPage_Text_UseProxy {
            get {
                return ResourceManager.GetString("ProxySettingPage.Text.UseProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use System Proxy 的當地語系化字串。
        /// </summary>
        public static string ProxySettingPage_Text_UseSystemProxy {
            get {
                return ResourceManager.GetString("ProxySettingPage.Text.UseSystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 About 的當地語系化字串。
        /// </summary>
        public static string SettingWindow_Text_About {
            get {
                return ResourceManager.GetString("SettingWindow.Text.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 App Setting 的當地語系化字串。
        /// </summary>
        public static string SettingWindow_Text_AppSetting {
            get {
                return ResourceManager.GetString("SettingWindow.Text.AppSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Proxy Setting 的當地語系化字串。
        /// </summary>
        public static string SettingWindow_Text_ProxySetting {
            get {
                return ResourceManager.GetString("SettingWindow.Text.ProxySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Settings 的當地語系化字串。
        /// </summary>
        public static string SettingWindow_Text_Title {
            get {
                return ResourceManager.GetString("SettingWindow.Text.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translate Setting 的當地語系化字串。
        /// </summary>
        public static string SettingWindow_Text_TranslateSetting {
            get {
                return ResourceManager.GetString("SettingWindow.Text.TranslateSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translate Window Setting 的當地語系化字串。
        /// </summary>
        public static string SettingWindow_Text_TranslateWindowSetting {
            get {
                return ResourceManager.GetString("SettingWindow.Text.TranslateWindowSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TTS Setting 的當地語系化字串。
        /// </summary>
        public static string SettingWindow_Text_TTSSetting {
            get {
                return ResourceManager.GetString("SettingWindow.Text.TTSSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Proxy 的當地語系化字串。
        /// </summary>
        public static string TranslateProviderSettingWindow_Text_Proxy {
            get {
                return ResourceManager.GetString("TranslateProviderSettingWindow.Text.Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use Proxy(If App Proxy Is Enabled) 的當地語系化字串。
        /// </summary>
        public static string TranslateProviderSettingWindow_Text_UseProxy {
            get {
                return ResourceManager.GetString("TranslateProviderSettingWindow.Text.UseProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Max Translate Word Count 的當地語系化字串。
        /// </summary>
        public static string TranslateSettingPage_Text_MaxTranslateWord {
            get {
                return ResourceManager.GetString("TranslateSettingPage.Text.MaxTranslateWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Source Language 的當地語系化字串。
        /// </summary>
        public static string TranslateSettingPage_Text_SourceLanguage {
            get {
                return ResourceManager.GetString("TranslateSettingPage.Text.SourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Target Language 的當地語系化字串。
        /// </summary>
        public static string TranslateSettingPage_Text_TargetLanguage {
            get {
                return ResourceManager.GetString("TranslateSettingPage.Text.TargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translate Interval 的當地語系化字串。
        /// </summary>
        public static string TranslateSettingPage_Text_TranslateInterval {
            get {
                return ResourceManager.GetString("TranslateSettingPage.Text.TranslateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translator Source 的當地語系化字串。
        /// </summary>
        public static string TranslateSettingPage_Text_TranslatorSource {
            get {
                return ResourceManager.GetString("TranslateSettingPage.Text.TranslatorSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Allow resize the window 的當地語系化字串。
        /// </summary>
        public static string TranslateWindow_Text_AllowResizeWindow {
            get {
                return ResourceManager.GetString("TranslateWindow.Text.AllowResizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exit 的當地語系化字串。
        /// </summary>
        public static string TranslateWindow_Text_Exit {
            get {
                return ResourceManager.GetString("TranslateWindow.Text.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Minimize the window 的當地語系化字串。
        /// </summary>
        public static string TranslateWindow_Text_MinimizeWindow {
            get {
                return ResourceManager.GetString("TranslateWindow.Text.MinimizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pause/Resume Translator 的當地語系化字串。
        /// </summary>
        public static string TranslateWindow_Text_PauseOrResumeTranslator {
            get {
                return ResourceManager.GetString("TranslateWindow.Text.PauseOrResumeTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please Select Hook Code First 的當地語系化字串。
        /// </summary>
        public static string TranslateWindow_Text_PleaseSelectHookItem {
            get {
                return ResourceManager.GetString("TranslateWindow.Text.PleaseSelectHookItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Read the source text aloud 的當地語系化字串。
        /// </summary>
        public static string TranslateWindow_Text_ReadAloud {
            get {
                return ResourceManager.GetString("TranslateWindow.Text.ReadAloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Re-translate 的當地語系化字串。
        /// </summary>
        public static string TranslateWindow_Text_ReTranslate {
            get {
                return ResourceManager.GetString("TranslateWindow.Text.ReTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select Hook Code 的當地語系化字串。
        /// </summary>
        public static string TranslateWindow_Text_SelectHookCode {
            get {
                return ResourceManager.GetString("TranslateWindow.Text.SelectHookCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select process 的當地語系化字串。
        /// </summary>
        public static string TranslateWindow_Text_SelectProcess {
            get {
                return ResourceManager.GetString("TranslateWindow.Text.SelectProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Setting 的當地語系化字串。
        /// </summary>
        public static string TranslateWindow_Text_Setting {
            get {
                return ResourceManager.GetString("TranslateWindow.Text.Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show history 的當地語系化字串。
        /// </summary>
        public static string TranslateWindow_Text_ShowHistory {
            get {
                return ResourceManager.GetString("TranslateWindow.Text.ShowHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show source text 的當地語系化字串。
        /// </summary>
        public static string TranslateWindow_Text_ShowSourceText {
            get {
                return ResourceManager.GetString("TranslateWindow.Text.ShowSourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Toggle OnTop 的當地語系化字串。
        /// </summary>
        public static string TranslateWindow_Text_ToggleOnTop {
            get {
                return ResourceManager.GetString("TranslateWindow.Text.ToggleOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Transparent 的當地語系化字串。
        /// </summary>
        public static string TranslateWindow_Text_Transparent {
            get {
                return ResourceManager.GetString("TranslateWindow.Text.Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Wait source text 的當地語系化字串。
        /// </summary>
        public static string TranslateWindow_Text_WaitSourceText {
            get {
                return ResourceManager.GetString("TranslateWindow.Text.WaitSourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable Text Shadow 的當地語系化字串。
        /// </summary>
        public static string TranslateWindowSettingPage_Text_EnableTextShadow {
            get {
                return ResourceManager.GetString("TranslateWindowSettingPage.Text.EnableTextShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Font Color 的當地語系化字串。
        /// </summary>
        public static string TranslateWindowSettingPage_Text_FontColor {
            get {
                return ResourceManager.GetString("TranslateWindowSettingPage.Text.FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Font Family 的當地語系化字串。
        /// </summary>
        public static string TranslateWindowSettingPage_Text_FontFamily {
            get {
                return ResourceManager.GetString("TranslateWindowSettingPage.Text.FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Font Size 的當地語系化字串。
        /// </summary>
        public static string TranslateWindowSettingPage_Text_FontSize {
            get {
                return ResourceManager.GetString("TranslateWindowSettingPage.Text.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select Color 的當地語系化字串。
        /// </summary>
        public static string TranslateWindowSettingPage_Text_SelectColor {
            get {
                return ResourceManager.GetString("TranslateWindowSettingPage.Text.SelectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Source Text Font Style 的當地語系化字串。
        /// </summary>
        public static string TranslateWindowSettingPage_Text_SourceTextFontStyle {
            get {
                return ResourceManager.GetString("TranslateWindowSettingPage.Text.SourceTextFontStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Window Color 的當地語系化字串。
        /// </summary>
        public static string TranslateWindowSettingPage_Text_WindowColor {
            get {
                return ResourceManager.GetString("TranslateWindowSettingPage.Text.WindowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select Voice 的當地語系化字串。
        /// </summary>
        public static string TTSSettingPage_Text_SelectVoice {
            get {
                return ResourceManager.GetString("TTSSettingPage.Text.SelectVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Speed(-10~10) 的當地語系化字串。
        /// </summary>
        public static string TTSSettingPage_Text_Speed {
            get {
                return ResourceManager.GetString("TTSSettingPage.Text.Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Test 的當地語系化字串。
        /// </summary>
        public static string TTSSettingPage_Text_TestVoice {
            get {
                return ResourceManager.GetString("TTSSettingPage.Text.TestVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Volume(0~100) 的當地語系化字串。
        /// </summary>
        public static string TTSSettingPage_Text_Volume {
            get {
                return ResourceManager.GetString("TTSSettingPage.Text.Volume", resourceCulture);
            }
        }
    }
}
